[package]
name = "iryna"
version = "0.1.0"
authors = ["archerfeel <archerfeel@gmail.com>"]
description = "A work-in-progress networking library."
license = "MIT"

[dependencies]
mio = "0.6"
concurrent-hashmap = "0.2.1"